### ISSUE TITLE
Highlights - Hand Driving

### ISSUE THREAD

**Issue by RobKoda** [infocris/geoguessr-helper#2]
Quand on hover sur les zones Left-hand driving et Right hand driving, seul les pays conduisant à gauche sont highlightés. 
En revanche, quand on clique dessus, les bons pays sont sélectionnés

![HandDrivingIssue](https://user-images.githubusercontent.com/43469854/110453112-25251800-80c6-11eb-95e4-dab53ac5f64a.gif)

**Comment by infocris** [comment]
Bug corrigé. Merci pour ta participation.
